#!/bin/sh
apk add --quiet eudev openrc udev-init-scripts udev-init-scripts-openrc
rc-update add udev sysinit
rc-update add udev-trigger sysinit
rc-update add udev-settle sysinit
rc-update add udev-postmount default
