#!/bin/sh
apk update
apk upgrade
# install xorg
apk add xorg-server xf86-input-libinput eudev mesa-dri-gallium
# kde
apk add plasma-desktop systemsettings sddm breeze
apk add ark dolphin konsole spectacle
# apps
apk add nano konqueror ca-certificates
# logind and other stuff
apk add elogind polkit-elogind dbus wpa_supplicant networkmanager \
    bluez networkmanager-wifi networkmanager-tui librsvg fuse
# pipewire
apk add wireplumber pipewire pipewire-pulse pipewire-alsa pipewire-spa-bluez \
    pipewire-jack pipewire-spa-tools

rc-update add dbus
rc-update add bluetooth
rc-update add networkmanager
rc-update add wpa_supplicant
rc-update add sddm
rc-update add udev
rc-update add elogind
rc-update add fuse
