#!/bin/bash
set -ex
apk add parted dialog coreutils
# install turkman linux installer
rm -f /sbin/init
wget https://gitlab.com/turkman/devel/sources/installer/-/raw/master/main.sh -O /sbin/init
chmod 755 /sbin/init
sed -i "s|/sbin/openrc-init|/bin/busybox init|g" /sbin/init
sed -i "s|openrc-init|busybox|g" /sbin/init
# change default username
sed -i "s/pingu/sagopa/g" /sbin/init
# grub settings
echo 'GRUB_CMDLINE_LINUX_DEFAULT="quiet rootfstype=ext4 modules=sd-mod,usb-storage,ext4"' > /etc/default/grub
sed -i "s/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/g" /etc/default/grub
# add initrd update hook
mkdir -p /etc/sysconf.d
cat > /etc/sysconf.d/installer <<EOF
#!/bin/bash
for dir in $(ls /lib/modules) ; do
    mkinitfs $dir
done
EOF
